version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/transferwise/tlint
    steps:
      - checkout
      - run:
          name: Dependencies
          command: go mod tidy
      - run:
          name: Build
          command: make build
  release:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/transferwise/tlint
    steps:
      - checkout
      - run:
          name: Dependencies
          command: go mod tidy
      - run:
          name: Build cross binaries
          command: make release
      - run:
          name: Publish Release on GitHub
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(cat VERSION.txt)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./cross/
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
